name: Coverage

# trigger on every commit push and PR for all branches
on:
  push:
    branches: ['**']
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: ['**']
    paths-ignore:
      - '**/*.md'
jobs:
  code-coverage:
    name: Code coverage
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Yarn
        run: |
          npm uninstall -g yarn
          npm i -g yarn@1.22.10

      - name: Install
        run: |
          yarn install

      - name: Code coverage report
        run: |
          yarn test:coverage-report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.lcov
          fail_ci_if_error: true

      - name: Code coverage 90%
        run: |
          yarn test:coverage-90
